package songmanager;

import java.io.File;
import java.io.FileWriter;
import java.util.List;

import org.jdom2.Attribute;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.input.SAXBuilder;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

public class EofRepacker {

	public EofRepacker() {
		
	}
	
	/**
	 * Converts an RS2 Bass XML file generated by Editor on Fire into a SongObject
	 * @param inputPath Path of the input XML file (expected as "~/PART REAL_BASS_RS2.xml")
	 */
	public SongObject GetSongObjectFromBassFile(String inputPath) {
		try {
			// Create document from file
			SAXBuilder saxBuilder = new SAXBuilder();
			File inputFile = new File(inputPath);
			Document doc = saxBuilder.build(inputFile);
			
			// Set up variables for song information
			String title, artist;
			int songLength, startBeat, averageTempo;
			Note[] notes;
			Beat[] beats;			
			
			// Retrieve singular elements
			Element songElement = doc.getRootElement();
			title = songElement.getChild("title").getText();
			artist = songElement.getChild("artistName").getText();
			averageTempo = Math.round(Float.valueOf(songElement.getChild("averageTempo").getText()) * 1000);
			songLength = Math.round(Float.valueOf(songElement.getChild("songLength").getText()) * 1000);
			startBeat = Math.round(Float.valueOf(songElement.getChild("startBeat").getText()) * 1000);
			
			// Retrieve beats
			Element beatsElement = songElement.getChild("ebeats");
			int beatCount = beatsElement.getAttribute("count").getIntValue();
			List<Element> beatElements = beatsElement.getChildren();
			beats = new Beat[beatCount];
			
			for (int i = 0; i < beatElements.size(); i++) {
				int time = Math.round(beatElements.get(i).getAttribute("time").getFloatValue() * 1000);
				int measure = beatElements.get(i).getAttribute("measure").getIntValue();
				beats[i] = new Beat(time, measure);
			}
			
			// Retrieve notes
			Element levelElement = songElement.getChild("levels").getChild("level");
			Element notesElement = levelElement.getChild("notes");
			Element chordsElement = levelElement.getChild("chords");
			Element handShapesElement = levelElement.getChild("handShapes");
			
			List<Element> noteElements = notesElement.getChildren();
			List<Element> chordElements = chordsElement.getChildren();
			List<Element> handShapeElements = handShapesElement.getChildren();
			
			int singleNoteCount = notesElement.getAttribute("count").getIntValue();
			int chordCount = chordsElement.getAttribute("count").getIntValue();
			int noteCount = singleNoteCount + chordCount;
			notes = new Note[noteCount];
			
			for (int i = 0; i < singleNoteCount; i++) {
				int time = Math.round(noteElements.get(i).getAttribute("time").getFloatValue() * 1000);
				int sustain = Math.round(noteElements.get(i).getAttribute("sustain").getFloatValue() * 1000);
				int string = noteElements.get(i).getAttribute("string").getIntValue();
				int[] buttons = {string};
				
				Note note = new Note(time, sustain, buttons);
				notes[i] = note;
			}
			
			for (int i = 0; i < chordCount; i++) {
				Element handShapeElement = handShapeElements.get(i);
				Element chordElement = chordElements.get(i);
				List<Element> chordNoteElements = chordElement.getChildren();
				
				int startTime = Math.round(handShapeElement.getAttribute("startTime").getFloatValue() * 1000);
				int endTime = Math.round(handShapeElement.getAttribute("endTime").getFloatValue() * 1000);
				int sustain = endTime - startTime;
				
				int[] buttons = new int[chordNoteElements.size()];
				for (int j = 0; j < chordNoteElements.size(); j++) {
					buttons[j] = chordNoteElements.get(j).getAttribute("string").getIntValue();
				}
				
				Note chord = new Note(startTime, sustain, buttons);
				notes[singleNoteCount + i] = chord;
			}
			
			// Create and return a SongObject
			SongObject obj = new SongObject(title, artist, songLength, averageTempo, notes, beats);
			return obj;
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}
	
	/**
	 * Converts a SongObject into an XML file
	 * @param Obj SongObject
	 * @param outputPath Path to write file to
	 */
	public void WriteSongObjectToXML(SongObject obj, String outputPath) {
		//title, artist, songlength, averagetempo, notes(time, sustain, button), beats(time, measure)
		try {
			// Root element
			Element songElement = new Element("song");
			Document doc = new Document(songElement);
			
			// Singular elements
			Element titleElement = new Element("title");
			titleElement.setText(obj.getTitle());
			songElement.addContent(titleElement);
			
			Element artistElement = new Element("artist");
			artistElement.setText(obj.getArtist());
			songElement.addContent(artistElement);
			
			Element songLengthElement = new Element("songLength");
			songLengthElement.setText(String.valueOf(obj.getSongLength()));
			songElement.addContent(songLengthElement);
			
			Element averageTempoElement = new Element("averageTempo");
			averageTempoElement.setText(String.valueOf(obj.getAverageTempo()));
			songElement.addContent(averageTempoElement);
			
			// Beat elements
			Element beatsElement = new Element("beats");
			Beat[] beats = obj.getBeats();
			for (int i = 0; i < beats.length; i++) {
				Element beatElement = new Element("beat");
				beatElement.setAttribute(new Attribute("time", String.valueOf(beats[i].getTime())));
				beatElement.setAttribute(new Attribute("measure", String.valueOf(beats[i].getMeasure())));
				beatsElement.addContent(beatElement);
			}
			songElement.addContent(beatsElement);
			
			// Note elements
			Element notesElement = new Element("notes");
			Note[] notes = obj.getNotes();
			for (int i = 0; i < notes.length; i++) {
				Element noteElement = new Element("note");
				noteElement.setAttribute(new Attribute("time", String.valueOf(notes[i].getTime())));
				noteElement.setAttribute(new Attribute("sustain", String.valueOf(notes[i].getSustain())));
				
				int[] buttons = notes[i].getButtons();
				for (int j = 0; j < 4; j++) {
					boolean inList = false;
					for (int k = 0; k < buttons.length; k++) {
						if (buttons[k] == j) {
							inList = true;
						}
					}
					
					if (inList) {
						noteElement.setAttribute(new Attribute("button" + j, "1"));
					} else {
						noteElement.setAttribute(new Attribute("button" + j, "0"));
					}
				}
				
				notesElement.addContent(noteElement);
			}
			songElement.addContent(notesElement);
			
			// Output XML
			XMLOutputter xmlOutput = new XMLOutputter();
			xmlOutput.setFormat(Format.getCompactFormat());
			xmlOutput.output(doc, new FileWriter(outputPath));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}




















